services:
    Gadget\Console\:
        autowire: true
        autoconfigure: true
        resource: '%kernel.project_dir%/vendor/mjfk23/gadget-console/src/'

    Gadget\Console\Shell\ProcessShellEnv:
        arguments:
            $workDir: '%kernel.project_dir%'
