TRUNCATE TABLE BNR_GORPRAC;
INSERT INTO BNR_GORPRAC
  (
    GORPRAC_PIDM,
    GORPRAC_RACE_CDE,
    GORRACE_DESC
  )
SELECT
  GORPRAC_PIDM AS GORPRAC_PIDM,
  MIN(GORPRAC_RACE_CDE) AS GORPRAC_RACE_CDE,
  MIN(GORRACE_DESC) AS GORRACE_DESC
FROM
  GORPRAC@BIPROD_BREPT_LINK_MFOREST,
  GORRACE@BIPROD_BREPT_LINK_MFOREST
WHERE
  GORRACE_RACE_CDE(+) = GORPRAC_RACE_CDE
GROUP BY
  GORPRAC_PIDM
HAVING
  COUNT(DISTINCT GORPRAC_RACE_CDE) = 1
UNION
SELECT
  GORPRAC_PIDM AS GORPRAC_PIDM,
  LISTAGG(DISTINCT GORPRAC_RACE_CDE) WITHIN GROUP(ORDER BY GORPRAC_RACE_CDE) AS GORPRAC_RACE_CDE,
  '2 or More Races' AS GORRACE_DESC
FROM
  GORPRAC@BIPROD_BREPT_LINK_MFOREST
GROUP BY
  GORPRAC_PIDM
HAVING
  COUNT(DISTINCT GORPRAC_RACE_CDE) > 1
;

COMMIT;

QUIT;
