TRUNCATE TABLE BNR_SGBSTDN;
INSERT INTO BNR_SGBSTDN
  (
    SPRIDEN_PIDM,
    SPRIDEN_ID,
    SGBSTDN_TERM_CODE_EFF,
    SGBSTDN_STST_CODE,
    SGBSTDN_STYP_CODE,
    SGBSTDN_LEVL_CODE,
    SGBSTDN_CAMP_CODE,
    SGBSTDN_COLL_CODE_1,
    SGBSTDN_DEPT_CODE,
    SGBSTDN_DEGC_CODE_1,
    SGBSTDN_MAJR_CODE_1,
    SGBSTDN_MAJR_CODE_CONC_1,
    SGBSTDN_PROGRAM_1,
    SGBSTDN_ACTIVITY_DATE,
    SPBPERS_SEX,
    SPBPERS_AGE,
    SPBPERS_ETHN_CODE,
    STU_LEVEL_REGENTS
  )
SELECT
  SPRIDEN_PIDM,
  SPRIDEN_ID,
  SGBSTDN_TERM_CODE_EFF,
  SGBSTDN_STST_CODE,
  SGBSTDN_STYP_CODE,
  SGBSTDN_LEVL_CODE,
  SGBSTDN_CAMP_CODE,
  SGBSTDN_COLL_CODE_1,
  SGBSTDN_DEPT_CODE,
  SGBSTDN_DEGC_CODE_1,
  SGBSTDN_MAJR_CODE_1,
  SGBSTDN_MAJR_CODE_CONC_1,
  SGBSTDN_PROGRAM_1,
  SGBSTDN_ACTIVITY_DATE,
  SPBPERS_SEX,
  FLOOR((SYSDATE - SPBPERS_BIRTH_DATE) / 365) AS SPBPERS_AGE,
  SPBPERS_ETHN_CODE,
  CASE
    WHEN SGBSTDN_LEVL_CODE = 'VT' THEN '05'
    WHEN SGBSTDN_LEVL_CODE IN ('FP','LW','LS','LQ') THEN '80'
    WHEN SGBSTDN_LEVL_CODE = 'GS' AND SGBSTDN_STYP_CODE in ('K','W','ND','TRG','CERM','CERG') THEN '60'
    WHEN SGBSTDN_LEVL_CODE = 'GS' THEN '70'
    WHEN SGBSTDN_LEVL_CODE = 'TRN' THEN '50'
    WHEN SGBSTDN_LEVL_CODE = 'B' THEN '51'
    WHEN SGBSTDN_LEVL_CODE = 'US' AND SGBSTDN_STYP_CODE = 'A' THEN '52'
    WHEN SGBSTDN_LEVL_CODE = 'US' AND SGBSTDN_STYP_CODE IN ('J', 'D') THEN '11'
    WHEN SGBSTDN_LEVL_CODE = 'US' AND SGBSTDN_STYP_CODE IN ('K', 'W') THEN '51'
    WHEN SGBSTDN_LEVL_CODE = 'US' AND SGBSTDN_STYP_CODE < '30' THEN '10'
    WHEN SGBSTDN_LEVL_CODE = 'US' AND (SGBSTDN_STYP_CODE >= '30' AND SGBSTDN_STYP_CODE < '60') THEN '20'
    WHEN SGBSTDN_LEVL_CODE = 'US' AND (SGBSTDN_STYP_CODE >= '60' AND SGBSTDN_STYP_CODE < '90') THEN '30'
    WHEN SGBSTDN_LEVL_CODE = 'US' AND SGBSTDN_STYP_CODE >= '90' THEN '40'
    WHEN SGBSTDN_LEVL_CODE = 'UA' AND SGBSTDN_STYP_CODE = 'X' THEN '50'
    WHEN SGBSTDN_LEVL_CODE = 'UA' AND SGBSTDN_STYP_CODE IN ('J', 'D') THEN '11'
    WHEN SGBSTDN_LEVL_CODE = 'UA' AND SGBSTDN_STYP_CODE IN ('B', 'N') THEN '51'
    WHEN SGBSTDN_LEVL_CODE = 'UA' AND SGBSTDN_STYP_CODE < '30' THEN '10'
    WHEN SGBSTDN_LEVL_CODE = 'UA' AND SGBSTDN_STYP_CODE >= '30' THEN '20'
    ELSE '10'
  END AS STU_LEVEL_REGENTS
FROM
  SPRIDEN@BIPROD_BREPT_LINK_MFOREST,
  SPBPERS@BIPROD_BREPT_LINK_MFOREST,
  (
    SELECT
      O.SGBSTDN_PIDM,
      O.SGBSTDN_TERM_CODE_EFF,
      O.SGBSTDN_STST_CODE,
      O.SGBSTDN_STYP_CODE,
      O.SGBSTDN_LEVL_CODE,
      O.SGBSTDN_COLL_CODE_1,
      O.SGBSTDN_DEPT_CODE,
      O.SGBSTDN_DEGC_CODE_1,
      O.SGBSTDN_MAJR_CODE_1,
      O.SGBSTDN_MAJR_CODE_CONC_1,
      O.SGBSTDN_PROGRAM_1,
      O.SGBSTDN_ACTIVITY_DATE,
      BANINST1.F_PRIMARY_CAMPUS@BIPROD_BREPT_LINK_MFOREST(O.SGBSTDN_PIDM, O.SGBSTDN_TERM_CODE_EFF) AS SGBSTDN_CAMP_CODE
    FROM
      SGBSTDN@BIPROD_BREPT_LINK_MFOREST O
    WHERE
      SGBSTDN_TERM_CODE_EFF = (
        SELECT
          MAX(I.SGBSTDN_TERM_CODE_EFF)
        FROM
          SGBSTDN@BIPROD_BREPT_LINK_MFOREST I
        WHERE
          I.SGBSTDN_PIDM = O.SGBSTDN_PIDM AND
          I.SGBSTDN_TERM_CODE_EFF <= (
            SELECT
              MIN(STVTERM_CODE)
            FROM
              STVTERM@BIPROD_BREPT_LINK_MFOREST
            WHERE
              STVTERM_END_DATE + 1 > SYSDATE
          )
      )
  ) SGBSTDN
WHERE
  SPRIDEN_CHANGE_IND IS NULL AND
  SPRIDEN_ENTITY_IND = 'P' AND
  SPBPERS_PIDM(+) = SPRIDEN_PIDM AND
  SGBSTDN_PIDM = SPRIDEN_PIDM
;

COMMIT;

QUIT;