MERGE INTO
  SISSECT A
USING
  (
    SELECT
      SSBSECT_TERM_CODE AS SISSECT_TERM_CODE,
      SSBSECT_CRN AS SISSECT_CRN,
      SSBSECT_SUBJ_CODE AS SISSECT_SUBJ_CODE,
      SSBSECT_CRSE_NUMB AS SISSECT_CRSE_NUMB,
      SSBSECT_SEQ_NUMB AS SISSECT_SEQ_NUMB,
      SSBSECT_CRSE_TITLE AS SISSECT_TITLE,
      SCBCRSE_EFF_TERM AS SISSECT_CRSE_EFF_TERM,
      SCBCRSE_TITLE AS SISSECT_CRSE_TITLE,
      SSRXLST_XLST_GROUP AS SISSECT_XLST_GROUP,
      NVL(SSBOVRR_DEPT_CODE, SCBCRSE_DEPT_CODE) AS SISSECT_DEPT_CODE,
      NVL(SSBOVRR_COLL_CODE, SCBCRSE_COLL_CODE) AS SISSECT_COLL_CODE,
      CASE SUBSTR(SSBSECT_TERM_CODE, -2)
        WHEN '01' THEN SUBSTR(SSBSECT_TERM_CODE, 0, 4) || '4'
        WHEN '05' THEN SUBSTR(SSBSECT_TERM_CODE + 100, 0, 4) || '1'
        WHEN '08' THEN SUBSTR(SSBSECT_TERM_CODE + 100, 0, 4) || '2'
      END AS SISSECT_TERM_OU_CODE,
      GREATEST(
        SSBSECT_ACTIVITY_DATE,
        SCBCRSE_ACTIVITY_DATE,
        NVL(SSBOVRR_ACTIVITY_DATE, DATE'1970-01-01'),
        NVL(SSRXLST_ACTIVITY_DATE, DATE'1970-01-01')
      ) AS SISSECT_ACTIVITY_DATE
    FROM
      STVTERM@BIPROD_BREPT_LINK_MFOREST,
      SSBSECT@BIPROD_BREPT_LINK_MFOREST,
      SCBCRSE@BIPROD_BREPT_LINK_MFOREST,
      SSBOVRR@BIPROD_BREPT_LINK_MFOREST,
      (
        SELECT
          SSRXLST_TERM_CODE,
          SSRXLST_CRN,
          MIN(SSRXLST_XLST_GROUP) AS SSRXLST_XLST_GROUP,
          MIN(SSRXLST_ACTIVITY_DATE) AS SSRXLST_ACTIVITY_DATE
        FROM
          SSRXLST@BIPROD_BREPT_LINK_MFOREST
        GROUP BY
          SSRXLST_TERM_CODE,
          SSRXLST_CRN
        HAVING
          COUNT(1) = 1
      ) SSRXLST
    WHERE
      STVTERM_START_DATE - 28 <= SYSDATE AND
      STVTERM_END_DATE + 14 >= SYSDATE AND
      SSBSECT_TERM_CODE = STVTERM_CODE AND
      SSBSECT_SSTS_CODE IN (
        SELECT
          STVSSTS_CODE
        FROM
          STVSSTS@BIPROD_BREPT_LINK_MFOREST
        WHERE
          STVSSTS_REG_IND = 'Y'
      ) AND
      SSBSECT_INTG_CDE IS NULL AND
      SCBCRSE_SUBJ_CODE = SSBSECT_SUBJ_CODE AND
      SCBCRSE_CRSE_NUMB = SSBSECT_CRSE_NUMB AND
      SCBCRSE_EFF_TERM = (
        SELECT
          MAX(i.SCBCRSE_EFF_TERM)
        FROM
          SCBCRSE@BIPROD_BREPT_LINK_MFOREST i
        WHERE
          i.SCBCRSE_SUBJ_CODE = SSBSECT_SUBJ_CODE AND
          i.SCBCRSE_CRSE_NUMB = SSBSECT_CRSE_NUMB AND
          i.SCBCRSE_EFF_TERM <= SSBSECT_TERM_CODE
      ) AND
      SSBOVRR_TERM_CODE(+) = SSBSECT_TERM_CODE AND
      SSBOVRR_CRN(+) = SSBSECT_CRN AND
      SSRXLST_TERM_CODE(+) = SSBSECT_TERM_CODE AND
      SSRXLST_CRN(+) = SSBSECT_CRN
  ) B
ON
  (
    A.SISSECT_TERM_CODE = B.SISSECT_TERM_CODE AND
    A.SISSECT_CRN = B.SISSECT_CRN
  )
WHEN MATCHED THEN
  UPDATE SET
    A.SISSECT_SUBJ_CODE = B.SISSECT_SUBJ_CODE,
    A.SISSECT_CRSE_NUMB = B.SISSECT_CRSE_NUMB,
    A.SISSECT_SEQ_NUMB = B.SISSECT_SEQ_NUMB,
    A.SISSECT_TITLE = B.SISSECT_TITLE,
    A.SISSECT_CRSE_EFF_TERM = B.SISSECT_CRSE_EFF_TERM,
    A.SISSECT_CRSE_TITLE = B.SISSECT_CRSE_TITLE,
    A.SISSECT_XLST_GROUP = B.SISSECT_XLST_GROUP,
    A.SISSECT_DEPT_CODE = B.SISSECT_DEPT_CODE,
    A.SISSECT_COLL_CODE = B.SISSECT_COLL_CODE,
    A.SISSECT_ACTIVITY_DATE = B.SISSECT_ACTIVITY_DATE,
    A.SISSECT_UPDATE_DATE = SYSDATE
  WHERE
    NVL(A.SISSECT_SUBJ_CODE, 0) != NVL(B.SISSECT_SUBJ_CODE, 0) OR
    NVL(A.SISSECT_CRSE_NUMB, 0) != NVL(B.SISSECT_CRSE_NUMB, 0) OR
    NVL(A.SISSECT_SEQ_NUMB, 0) != NVL(B.SISSECT_SEQ_NUMB, 0) OR
    NVL(A.SISSECT_TITLE, 0) != NVL(B.SISSECT_TITLE, 0) OR
    NVL(A.SISSECT_CRSE_EFF_TERM, 0) != NVL(B.SISSECT_CRSE_EFF_TERM, 0) OR
    NVL(A.SISSECT_CRSE_TITLE, 0) != NVL(B.SISSECT_CRSE_TITLE, 0) OR
    NVL(A.SISSECT_XLST_GROUP, 0) != NVL(B.SISSECT_XLST_GROUP, 0) OR
    NVL(A.SISSECT_DEPT_CODE, 0) != NVL(B.SISSECT_DEPT_CODE, 0) OR
    NVL(A.SISSECT_COLL_CODE, 0) != NVL(B.SISSECT_COLL_CODE, 0) OR
    NVL(A.SISSECT_ACTIVITY_DATE, SYSDATE) != NVL(B.SISSECT_ACTIVITY_DATE, SYSDATE)
WHEN NOT MATCHED THEN
  INSERT
    (
      A.SISSECT_TERM_CODE,
      A.SISSECT_CRN,
      A.SISSECT_SUBJ_CODE,
      A.SISSECT_CRSE_NUMB,
      A.SISSECT_SEQ_NUMB,
      A.SISSECT_TITLE,
      A.SISSECT_CRSE_EFF_TERM,
      A.SISSECT_CRSE_TITLE,
      A.SISSECT_XLST_GROUP,
      A.SISSECT_DEPT_CODE,
      A.SISSECT_COLL_CODE,
      A.SISSECT_TERM_OU_CODE,
      A.SISSECT_ACTIVITY_DATE,
      A.SISSECT_CREATE_DATE,
      A.SISSECT_UPDATE_DATE
    )
  VALUES
    (
      B.SISSECT_TERM_CODE,
      B.SISSECT_CRN,
      B.SISSECT_SUBJ_CODE,
      B.SISSECT_CRSE_NUMB,
      B.SISSECT_SEQ_NUMB,
      B.SISSECT_TITLE,
      B.SISSECT_CRSE_EFF_TERM,
      B.SISSECT_CRSE_TITLE,
      B.SISSECT_XLST_GROUP,
      B.SISSECT_DEPT_CODE,
      B.SISSECT_COLL_CODE,
      B.SISSECT_TERM_OU_CODE,
      B.SISSECT_ACTIVITY_DATE,
      SYSDATE,
      SYSDATE
    )
;

DELETE FROM
  SISSECT
WHERE
  EXISTS (
    SELECT
      1
    FROM
      SISTERM
    WHERE
      SISTERM_CODE = SISSECT_TERM_CODE AND
      SISTERM_START_DATE - 28 <= SYSDATE AND
      SISTERM_END_DATE + 14 >= SYSDATE
  ) AND
  NOT EXISTS (
    SELECT
      1
    FROM
      SSBSECT@BIPROD_BREPT_LINK_MFOREST
    WHERE
      SSBSECT_TERM_CODE = SISSECT_TERM_CODE AND
      SSBSECT_CRN = SISSECT_CRN AND
      SSBSECT_SSTS_CODE IN (
        SELECT
          STVSSTS_CODE
        FROM
          STVSSTS@BIPROD_BREPT_LINK_MFOREST
        WHERE
          STVSSTS_REG_IND = 'Y'
      ) AND
      SSBSECT_INTG_CDE IS NULL
  )
;


MERGE INTO
  SISSECT A
USING
  (
    SELECT
      SISSECT_TERM_CODE,
      SISSECT_CRN,
      CASE
        WHEN SISSECT_COLL_CODE IS NOT NULL THEN
          'COL.090.' || SISSECT_COLL_CODE 
      END AS SISSECT_COLL_OU_CODE, 
      CASE
        WHEN SISSECT_DEPT_CODE IS NOT NULL THEN
          'DEP' || SISSECT_DEPT_CODE 
      END AS SISSECT_DEPT_OU_CODE,
      CASE
        WHEN SISSECT_DEPT_CODE IS NOT NULL THEN
          '090.' || SISSECT_DEPT_CODE || '.' || SISSECT_SUBJ_CODE || SISSECT_CRSE_NUMB
      END AS SISSECT_TMPL_OU_CODE,
      CASE
        WHEN SISSECT_DEPT_CODE IS NOT NULL THEN
        CASE
          WHEN SISSECT_XLST_GROUP IS NOT NULL THEN
            'CO.090'
              || '.' || SISSECT_DEPT_CODE
              || '.' || SISSECT_SUBJ_CODE || SISSECT_CRSE_NUMB
              || '.XLS.' || SISSECT_XLST_GROUP
              || '.' || SISSECT_TERM_OU_CODE
          ELSE
            'CO.090'
              || '.' || SISSECT_DEPT_CODE
              || '.' || SISSECT_SUBJ_CODE || SISSECT_CRSE_NUMB
              || '.' || SISSECT_CRN
              || '.' || SISSECT_TERM_OU_CODE
        END
      END AS SISSECT_OFFR_OU_CODE,
      CASE
        WHEN SISSECT_DEPT_CODE IS NOT NULL THEN
          'SEC.090'
            || '.' || SISSECT_DEPT_CODE
            || '.' || SISSECT_SUBJ_CODE || SISSECT_CRSE_NUMB
            || '.' || SISSECT_CRN
            || '.' || SISSECT_TERM_OU_CODE
      END AS SISSECT_SECT_OU_CODE
    FROM
      SISSECT
  ) B
ON
  (
    A.SISSECT_TERM_CODE = B.SISSECT_TERM_CODE AND
    A.SISSECT_CRN = B.SISSECT_CRN
  )
WHEN MATCHED THEN
  UPDATE SET
    A.SISSECT_COLL_OU_CODE = B.SISSECT_COLL_OU_CODE,
    A.SISSECT_DEPT_OU_CODE = B.SISSECT_DEPT_OU_CODE,
    A.SISSECT_TMPL_OU_CODE = B.SISSECT_TMPL_OU_CODE,
    A.SISSECT_OFFR_OU_CODE = B.SISSECT_OFFR_OU_CODE,
    A.SISSECT_SECT_OU_CODE = B.SISSECT_SECT_OU_CODE
  WHERE
    NVL(A.SISSECT_COLL_OU_CODE, 0) != NVL(B.SISSECT_COLL_OU_CODE, 0) OR
    NVL(A.SISSECT_DEPT_OU_CODE, 0) != NVL(B.SISSECT_DEPT_OU_CODE, 0) OR
    NVL(A.SISSECT_TMPL_OU_CODE, 0) != NVL(B.SISSECT_TMPL_OU_CODE, 0) OR
    NVL(A.SISSECT_OFFR_OU_CODE, 0) != NVL(B.SISSECT_OFFR_OU_CODE, 0) OR
    NVL(A.SISSECT_SECT_OU_CODE, 0) != NVL(B.SISSECT_SECT_OU_CODE, 0)
;

COMMIT;

QUIT;
