MERGE INTO
  SISSTDN A
USING
  (
    SELECT
      SGBSTDN_PIDM             AS SISSTDN_PIDM,
      SGBSTDN_TERM_CODE_EFF    AS SISSTDN_TERM_CODE_EFF,
      SGBSTDN_STST_CODE        AS SISSTDN_STST_CODE,
      SGBSTDN_STYP_CODE        AS SISSTDN_STYP_CODE,
      SGBSTDN_COLL_CODE_1      AS SISSTDN_COLL_CODE_1,
      SGBSTDN_DEPT_CODE        AS SISSTDN_DEPT_CODE,
      SGBSTDN_DEGC_CODE_1      AS SISSTDN_DEGC_CODE_1,
      SGBSTDN_MAJR_CODE_1      AS SISSTDN_MAJR_CODE_1,
      SGBSTDN_MAJR_CODE_CONC_1 AS SISSTDN_MAJR_CODE_CONC_1,
      SGBSTDN_PROGRAM_1        AS SISSTDN_PROGRAM_1,
      SGBSTDN_LEVL_CODE        AS SISSTDN_LEVL_CODE,
      SPBPERS_BIRTH_DATE       AS SISSTDN_BIRTH_DATE,
      SPBPERS_SEX              AS SISSTDN_SEX,
      SPBPERS_ETHN_CODE        AS SISSTDN_ETHN_CODE,
      GORPRAC_RACE_CDE         AS SISSTDN_RACE_CDE,
      BANINST1.F_PRIMARY_CAMPUS@BIPROD_BREPT_LINK_MFOREST(
        SGBSTDN_PIDM,
        SGBSTDN_TERM_CODE_EFF
      ) AS SISSTDN_CAMP_CODE,
      CASE
        WHEN SGBSTDN_LEVL_CODE = 'VT' THEN '05'
        WHEN SGBSTDN_LEVL_CODE IN ('FP','LW','LS','LQ') THEN '80'
        WHEN SGBSTDN_LEVL_CODE = 'GS' AND SGBSTDN_STYP_CODE IN ('K','W','ND','TRG','CERM','CERG') THEN '60'
        WHEN SGBSTDN_LEVL_CODE = 'GS' THEN '70'
        WHEN SGBSTDN_LEVL_CODE = 'TRN' THEN '50'
        WHEN SGBSTDN_LEVL_CODE = 'B' THEN '51'
        WHEN SGBSTDN_LEVL_CODE = 'US' AND SGBSTDN_STYP_CODE = 'A' THEN '52'
        WHEN SGBSTDN_LEVL_CODE = 'US' AND SGBSTDN_STYP_CODE IN ('J', 'D') THEN '11'
        WHEN SGBSTDN_LEVL_CODE = 'US' AND SGBSTDN_STYP_CODE IN ('K', 'W') THEN '51'
        WHEN SGBSTDN_LEVL_CODE = 'US' AND SGBSTDN_STYP_CODE < '30' THEN '10'
        WHEN SGBSTDN_LEVL_CODE = 'US' AND (SGBSTDN_STYP_CODE >= '30' AND SGBSTDN_STYP_CODE < '60') THEN '20'
        WHEN SGBSTDN_LEVL_CODE = 'US' AND (SGBSTDN_STYP_CODE >= '60' AND SGBSTDN_STYP_CODE < '90') THEN '30'
        WHEN SGBSTDN_LEVL_CODE = 'US' AND SGBSTDN_STYP_CODE >= '90' THEN '40'
        WHEN SGBSTDN_LEVL_CODE = 'UA' AND SGBSTDN_STYP_CODE = 'X' THEN '50'
        WHEN SGBSTDN_LEVL_CODE = 'UA' AND SGBSTDN_STYP_CODE IN ('J', 'D') THEN '11'
        WHEN SGBSTDN_LEVL_CODE = 'UA' AND SGBSTDN_STYP_CODE IN ('B', 'N') THEN '51'
        WHEN SGBSTDN_LEVL_CODE = 'UA' AND SGBSTDN_STYP_CODE < '30' THEN '10'
        WHEN SGBSTDN_LEVL_CODE = 'UA' AND SGBSTDN_STYP_CODE >= '30' THEN '20'
        ELSE '10'
      END AS SISSTDN_REGENTS_LEVL_CODE,
      GREATEST(
        SGBSTDN_ACTIVITY_DATE,
        NVL(SPBPERS_ACTIVITY_DATE, DATE'1970-01-01'),
        NVL(GORPRAC_ACTIVITY_DATE, DATE'1970-01-01')
      ) AS SISSTDN_ACTIVITY_DATE
    FROM
      SPRIDEN@BIPROD_BREPT_LINK_MFOREST,
      SGBSTDN@BIPROD_BREPT_LINK_MFOREST,
      SPBPERS@BIPROD_BREPT_LINK_MFOREST,
      (
        SELECT
          GORPRAC_PIDM,
          LISTAGG(DISTINCT GORPRAC_RACE_CDE) WITHIN GROUP(ORDER BY GORPRAC_RACE_CDE) AS GORPRAC_RACE_CDE,
          CASE
            WHEN COUNT(DISTINCT GORPRAC_RACE_CDE) > 1 THEN '2 OR MORE RACES'
            ELSE MIN(GORRACE_DESC)
          END AS GORPRAC_DESC,
          MAX(GORPRAC_ACTIVITY_DATE) as GORPRAC_ACTIVITY_DATE
        FROM
          GORPRAC@BIPROD_BREPT_LINK_MFOREST,
          GORRACE@BIPROD_BREPT_LINK_MFOREST
        WHERE
          GORRACE_RACE_CDE(+) = GORPRAC_RACE_CDE
        GROUP BY
          GORPRAC_PIDM
      ) GORPRAC
    WHERE
      SPRIDEN_ENTITY_IND = 'P' AND
      SPRIDEN_CHANGE_IND IS NULL AND
      SGBSTDN_PIDM = SPRIDEN_PIDM AND
      SGBSTDN_TERM_CODE_EFF = (
        SELECT
          MAX(I.SGBSTDN_TERM_CODE_EFF)
        FROM
          SGBSTDN@BIPROD_BREPT_LINK_MFOREST I
        WHERE
          I.SGBSTDN_PIDM = SPRIDEN_PIDM AND
          I.SGBSTDN_TERM_CODE_EFF <= (
            SELECT
              MIN(STVTERM_CODE)
            FROM
              STVTERM@BIPROD_BREPT_LINK_MFOREST
            WHERE
              STVTERM_END_DATE + 1 >= SYSDATE
          )
      ) AND
      SPBPERS_PIDM(+) = SPRIDEN_PIDM AND
      GORPRAC_PIDM(+) = SPRIDEN_PIDM
  ) B
ON
  (
    A.SISSTDN_PIDM = B.SISSTDN_PIDM
  )
WHEN MATCHED THEN
  UPDATE SET
    A.SISSTDN_TERM_CODE_EFF = B.SISSTDN_TERM_CODE_EFF,
    A.SISSTDN_STST_CODE = B.SISSTDN_STST_CODE,
    A.SISSTDN_STYP_CODE = B.SISSTDN_STYP_CODE,
    A.SISSTDN_COLL_CODE_1 = B.SISSTDN_COLL_CODE_1,
    A.SISSTDN_DEPT_CODE = B.SISSTDN_DEPT_CODE,
    A.SISSTDN_DEGC_CODE_1 = B.SISSTDN_DEGC_CODE_1,
    A.SISSTDN_MAJR_CODE_1 = B.SISSTDN_MAJR_CODE_1,
    A.SISSTDN_MAJR_CODE_CONC_1 = B.SISSTDN_MAJR_CODE_CONC_1,
    A.SISSTDN_PROGRAM_1 = B.SISSTDN_PROGRAM_1,
    A.SISSTDN_LEVL_CODE = B.SISSTDN_LEVL_CODE,
    A.SISSTDN_CAMP_CODE = B.SISSTDN_CAMP_CODE,
    A.SISSTDN_BIRTH_DATE = B.SISSTDN_BIRTH_DATE,
    A.SISSTDN_SEX = B.SISSTDN_SEX,
    A.SISSTDN_ETHN_CODE = B.SISSTDN_ETHN_CODE,
    A.SISSTDN_RACE_CDE = B.SISSTDN_RACE_CDE,
    A.SISSTDN_REGENTS_LEVL_CODE = B.SISSTDN_REGENTS_LEVL_CODE,
    A.SISSTDN_ACTIVITY_DATE = B.SISSTDN_ACTIVITY_DATE,
    A.SISSTDN_UPDATE_DATE = SYSDATE
  WHERE
    NVL(A.SISSTDN_TERM_CODE_EFF, 0) != NVL(B.SISSTDN_TERM_CODE_EFF, 0) OR
    NVL(A.SISSTDN_STST_CODE, 0) != NVL(B.SISSTDN_STST_CODE, 0) OR
    NVL(A.SISSTDN_STYP_CODE, 0) != NVL(B.SISSTDN_STYP_CODE, 0) OR
    NVL(A.SISSTDN_COLL_CODE_1, 0) != NVL(B.SISSTDN_COLL_CODE_1, 0) OR
    NVL(A.SISSTDN_DEPT_CODE, 0) != NVL(B.SISSTDN_DEPT_CODE, 0) OR
    NVL(A.SISSTDN_DEGC_CODE_1, 0) != NVL(B.SISSTDN_DEGC_CODE_1, 0) OR
    NVL(A.SISSTDN_MAJR_CODE_1, 0) != NVL(B.SISSTDN_MAJR_CODE_1, 0) OR
    NVL(A.SISSTDN_MAJR_CODE_CONC_1, 0) != NVL(B.SISSTDN_MAJR_CODE_CONC_1, 0) OR
    NVL(A.SISSTDN_PROGRAM_1, 0) != NVL(B.SISSTDN_PROGRAM_1, 0) OR
    NVL(A.SISSTDN_LEVL_CODE, 0) != NVL(B.SISSTDN_LEVL_CODE, 0) OR
    NVL(A.SISSTDN_CAMP_CODE, 0) != NVL(B.SISSTDN_CAMP_CODE, 0) OR
    NVL(A.SISSTDN_BIRTH_DATE, SYSDATE) != NVL(B.SISSTDN_BIRTH_DATE, SYSDATE) OR
    NVL(A.SISSTDN_SEX, 0) != NVL(B.SISSTDN_SEX, 0) OR
    NVL(A.SISSTDN_ETHN_CODE, 0) != NVL(B.SISSTDN_ETHN_CODE, 0) OR
    NVL(A.SISSTDN_RACE_CDE, 0) != NVL(B.SISSTDN_RACE_CDE, 0) OR
    NVL(A.SISSTDN_REGENTS_LEVL_CODE, 0) != NVL(B.SISSTDN_REGENTS_LEVL_CODE, 0) OR
    NVL(A.SISSTDN_ACTIVITY_DATE, SYSDATE) != NVL(B.SISSTDN_ACTIVITY_DATE, SYSDATE)
WHEN NOT MATCHED THEN
  INSERT
    (
        A.SISSTDN_PIDM,
        A.SISSTDN_TERM_CODE_EFF,
        A.SISSTDN_STST_CODE,
        A.SISSTDN_STYP_CODE,
        A.SISSTDN_COLL_CODE_1,
        A.SISSTDN_DEPT_CODE,
        A.SISSTDN_DEGC_CODE_1,
        A.SISSTDN_MAJR_CODE_1,
        A.SISSTDN_MAJR_CODE_CONC_1,
        A.SISSTDN_PROGRAM_1,
        A.SISSTDN_LEVL_CODE,
        A.SISSTDN_CAMP_CODE,
        A.SISSTDN_BIRTH_DATE,
        A.SISSTDN_SEX,
        A.SISSTDN_ETHN_CODE,
        A.SISSTDN_RACE_CDE,
        A.SISSTDN_REGENTS_LEVL_CODE,
        A.SISSTDN_ACTIVITY_DATE,
        A.SISSTDN_CREATE_DATE,
        A.SISSTDN_UPDATE_DATE
    )
  VALUES
    (
        B.SISSTDN_PIDM,
        B.SISSTDN_TERM_CODE_EFF,
        B.SISSTDN_STST_CODE,
        B.SISSTDN_STYP_CODE,
        B.SISSTDN_COLL_CODE_1,
        B.SISSTDN_DEPT_CODE,
        B.SISSTDN_DEGC_CODE_1,
        B.SISSTDN_MAJR_CODE_1,
        B.SISSTDN_MAJR_CODE_CONC_1,
        B.SISSTDN_PROGRAM_1,
        B.SISSTDN_LEVL_CODE,
        B.SISSTDN_CAMP_CODE,
        B.SISSTDN_BIRTH_DATE,
        B.SISSTDN_SEX,
        B.SISSTDN_ETHN_CODE,
        B.SISSTDN_RACE_CDE,
        B.SISSTDN_REGENTS_LEVL_CODE,
        B.SISSTDN_ACTIVITY_DATE,
        SYSDATE,
        SYSDATE
    )
;

DELETE FROM
  SISSTDN A
WHERE
  NOT EXISTS (
    SELECT
      1
    FROM
      SGBSTDN@BIPROD_BREPT_LINK_MFOREST
    WHERE
      SGBSTDN_PIDM = SISSTDN_PIDM
  )
;

COMMIT;

QUIT;
