MERGE INTO
  SISUSER A
USING
  (
    SELECT
      GOBTPAC_EXTERNAL_USER AS SISUSER_CAMPUS_ID,
      GSUEMAL.GOREMAL_EMAIL_ADDRESS AS SISUSER_GSU_EMAIL,
      FSEEMAL.GOREMAL_EMAIL_ADDRESS AS SISUSER_FSEM_EMAIL,
      SPRIDEN_LAST_NAME AS SISUSER_LAST_NAME,
      SPRIDEN_FIRST_NAME AS SISUSER_FIRST_NAME,
      SPRIDEN_PIDM AS SISUSER_PIDM,
      SPRIDEN_ID AS SISUSER_PANTHER_ID,
      GOBSRID_SOURCED_ID AS SISUSER_SOURCED_ID,
      '090.' || GOBSRID_SOURCED_ID AS SISUSER_ORG_DEFINED_ID,
      GREATEST(
        GOBTPAC_ACTIVITY_DATE,
        GOBSRID_ACTIVITY_DATE,
        SPRIDEN_ACTIVITY_DATE,
        NVL(GSUEMAL.GOREMAL_ACTIVITY_DATE, DATE'1970-01-01'),
        NVL(FSEEMAL.GOREMAL_ACTIVITY_DATE, DATE'1970-01-01')
      ) AS SISUSER_ACTIVITY_DATE
    FROM
      GOBTPAC@BIPROD_BREPT_LINK_MFOREST,
      GOBSRID@BIPROD_BREPT_LINK_MFOREST,
      SPRIDEN@BIPROD_BREPT_LINK_MFOREST,
      GOREMAL@BIPROD_BREPT_LINK_MFOREST GSUEMAL,
      GOREMAL@BIPROD_BREPT_LINK_MFOREST FSEEMAL
    WHERE
      GOBTPAC_EXTERNAL_USER IS NOT NULL AND
      LENGTH(GOBTPAC_EXTERNAL_USER) >= 2 AND
      LENGTH(GOBTPAC_EXTERNAL_USER) <= 20 AND
      GOBSRID_PIDM = GOBTPAC_PIDM AND
      REGEXP_LIKE(GOBSRID_SOURCED_ID, '^[0-9]+$') AND
      SPRIDEN_PIDM = GOBTPAC_PIDM AND
      SPRIDEN_CHANGE_IND IS NULL AND
      GSUEMAL.GOREMAL_PIDM(+) = GOBTPAC_PIDM AND
      GSUEMAL.GOREMAL_EMAL_CODE(+) = 'GSU' AND
      GSUEMAL.GOREMAL_STATUS_IND(+) = 'A' AND
      FSEEMAL.GOREMAL_PIDM(+) = GOBTPAC_PIDM AND
      FSEEMAL.GOREMAL_EMAL_CODE(+) = 'FSEM' AND
      FSEEMAL.GOREMAL_STATUS_IND(+) = 'A'
  ) B
ON
  (
    A.SISUSER_PIDM = B.SISUSER_PIDM
  )
WHEN MATCHED THEN
  UPDATE SET
    A.SISUSER_CAMPUS_ID = B.SISUSER_CAMPUS_ID,
    A.SISUSER_GSU_EMAIL = B.SISUSER_GSU_EMAIL,
    A.SISUSER_FSEM_EMAIL = B.SISUSER_FSEM_EMAIL,
    A.SISUSER_FIRST_NAME = B.SISUSER_FIRST_NAME,
    A.SISUSER_LAST_NAME = B.SISUSER_LAST_NAME,
    A.SISUSER_PANTHER_ID = B.SISUSER_PANTHER_ID,
    A.SISUSER_SOURCED_ID = B.SISUSER_SOURCED_ID,
    A.SISUSER_ORG_DEFINED_ID = B.SISUSER_ORG_DEFINED_ID,
    A.SISUSER_ACTIVITY_DATE = B.SISUSER_ACTIVITY_DATE,
    A.SISUSER_UPDATE_DATE = SYSDATE
  WHERE
    A.SISUSER_CAMPUS_ID != B.SISUSER_CAMPUS_ID OR
    NVL(A.SISUSER_GSU_EMAIL, 0) != NVL(B.SISUSER_GSU_EMAIL, 0) OR
    NVL(A.SISUSER_FSEM_EMAIL, 0) != NVL(B.SISUSER_FSEM_EMAIL, 0) OR
    NVL(A.SISUSER_FIRST_NAME, 0) != NVL(B.SISUSER_FIRST_NAME, 0) OR
    A.SISUSER_LAST_NAME != B.SISUSER_LAST_NAME OR
    A.SISUSER_PANTHER_ID != B.SISUSER_PANTHER_ID OR
    A.SISUSER_SOURCED_ID != B.SISUSER_SOURCED_ID OR
    A.SISUSER_ORG_DEFINED_ID != B.SISUSER_ORG_DEFINED_ID OR
    A.SISUSER_ACTIVITY_DATE != B.SISUSER_ACTIVITY_DATE
WHEN NOT MATCHED THEN
  INSERT
    (
      A.SISUSER_CAMPUS_ID,
      A.SISUSER_GSU_EMAIL,
      A.SISUSER_FSEM_EMAIL,
      A.SISUSER_FIRST_NAME,
      A.SISUSER_LAST_NAME,
      A.SISUSER_PIDM,
      A.SISUSER_PANTHER_ID,
      A.SISUSER_SOURCED_ID,
      A.SISUSER_ORG_DEFINED_ID,
      A.SISUSER_ACTIVITY_DATE,
      A.SISUSER_CREATE_DATE,
      A.SISUSER_UPDATE_DATE
    )
  VALUES
    (
      B.SISUSER_CAMPUS_ID,
      B.SISUSER_GSU_EMAIL,
      B.SISUSER_FSEM_EMAIL,
      B.SISUSER_FIRST_NAME,
      B.SISUSER_LAST_NAME,
      B.SISUSER_PIDM,
      B.SISUSER_PANTHER_ID,
      B.SISUSER_SOURCED_ID,
      B.SISUSER_ORG_DEFINED_ID,
      B.SISUSER_ACTIVITY_DATE,
      SYSDATE,
      SYSDATE
    )
;

DELETE FROM
  SISUSER
WHERE
  NOT EXISTS (
    SELECT
      1
    FROM
      GOBTPAC@BIPROD_BREPT_LINK_MFOREST,
      GOBSRID@BIPROD_BREPT_LINK_MFOREST,
      SPRIDEN@BIPROD_BREPT_LINK_MFOREST
    WHERE
      GOBTPAC_PIDM = SISUSER_PIDM AND
      GOBTPAC_EXTERNAL_USER IS NOT NULL AND
      LENGTH(GOBTPAC_EXTERNAL_USER) >= 2 AND
      LENGTH(GOBTPAC_EXTERNAL_USER) <= 20 AND
      GOBSRID_PIDM = GOBTPAC_PIDM AND
      REGEXP_LIKE(GOBSRID_SOURCED_ID, '^[0-9]+$') AND
      SPRIDEN_PIDM = GOBTPAC_PIDM AND
      SPRIDEN_CHANGE_IND IS NULL
  )
;

COMMIT;

QUIT;
