TRUNCATE TABLE SKILL_ASSESSMENT;

INSERT INTO SKILL_ASSESSMENT
  (
    SKILL_ASSESSMENT_PROGRAM_ID,
    SKILL_ASSESSMENT_PROGRAM_NAME,
    SKILL_ASSESSMENT_DETAIL_ID,
    SKILL_ASSESSMENT_DETAIL_DESCRIPTION,
    SKILL_ASSESSMENT_DETAIL_PARENT_ID,
    SKILL_ASSESSMENT_DETAIL_SOURCE,
    SKILL_ASSESSMENT_REGISTRY_ID,
    SKILL_ASSESSMENT_COURSE_ID,
    SKILL_ASSESSMENT_COURSE_TYPE,
    SKILL_ASSESSMENT_COURSE_CODE,
    SKILL_ASSESSMENT_COURSE_NAME,
    SKILL_ASSESSMENT_ID,
    SKILL_ASSESSMENT_DATE,
    SKILL_ASSESSMENT_ASSESSED_USER_ID,
    SKILL_ASSESSMENT_ASSESSOR_USER_ID,
    SKILL_ASSESSMENT_ALIGNED_OBJECT_TYPE,
    SKILL_ASSESSMENT_ALIGNED_OBJECT_ID,
    SKILL_ASSESSMENT_LEVEL_ID,
    SKILL_ASSESSMENT_LEVEL_NAME,
    SKILL_ASSESSMENT_LEVEL_VALUE
  )
SELECT
  SKILL_DETAIL_PROGRAM_ID AS SKILL_ASSESSMENT_PROGRAM_ID,
  SKILL_DETAIL_PROGRAM_NAME AS SKILL_ASSESSMENT_PROGRAM_NAME,
  SKILL_DETAIL_ID AS SKILL_ASSESSMENT_DETAIL_ID,
  SKILL_DETAIL_DESCRIPTION AS SKILL_ASSESSMENT_DETAIL_DESCRIPTION,
  SKILL_DETAIL_PARENT_ID AS SKILL_ASSESSMENT_DETAIL_PARENT_ID,
  SKILL_DETAIL_SOURCE AS SKILL_ASSESSMENT_DETAIL_SOURCE,
  OutcomeDemonstration.RegistryId AS SKILL_ASSESSMENT_REGISTRY_ID,
  OrgUnit.OrgUnitId AS SKILL_ASSESSMENT_COURSE_ID,
  OrgUnit.Type AS SKILL_ASSESSMENT_COURSE_TYPE,
  OrgUnit.Code AS SKILL_ASSESSMENT_COURSE_CODE,
  OrgUnit.Name AS SKILL_ASSESSMENT_COURSE_NAME,
  OutcomeDemonstration.DemonstrationId AS SKILL_ASSESSMENT_ID,
  OutcomeDemonstration.AssessedDate as SKILL_ASSESSMENT_DATE,
  OutcomeDemonstration.AssessedUserId as SKILL_ASSESSMENT_ASSESSED_USER_ID,
  OutcomeDemonstration.AssessorUserId as SKILL_ASSESSMENT_ASSESSOR_USER_ID,
  CASE OutcomeDemonstration.AlignedObjectType
    WHEN 1 THEN 'Discussion'
    WHEN 2 THEN 'Assignment'
    WHEN 3 THEN 'Quiz'
  END AS SKILL_ASSESSMENT_ALIGNED_OBJECT_TYPE,
  OutcomeDemonstration.AlignedObjectId AS SKILL_ASSESSMENT_ALIGNED_OBJECT_ID,
  SKILL_LEVEL_ID AS SKILL_ASSESSMENT_LEVEL_ID,
  SKILL_LEVEL_NAME AS SKILL_ASSESSMENT_LEVEL_NAME,
  SKILL_LEVEL_PCTSTART AS SKILL_ASSESSMENT_LEVEL_VALUE
FROM
  SKILL_DETAIL SkillDetail,
  D2L_OUTCOMES_DEMONSTRATION OutcomeDemonstration,
  D2L_OUTCOME_REGISTRY_OWNER OutcomeRegistryOwner,
  D2L_ORGANIZATIONAL_UNIT OrgUnit,
  SKILL_LEVEL SkillLevel
WHERE
  OutcomeDemonstration.OutcomeId = SKILL_DETAIL_ID AND
  OutcomeDemonstration.AssessedDate IS NOT NULL AND
  OutcomeDemonstration.AssessedUserId IS NOT NULL AND
  OutcomeDemonstration.AssessorUserId IS NOT NULL AND
  OutcomeDemonstration.AlignedObjectType in (1, 2, 3, 5) AND
  OutcomeDemonstration.AlignedObjectId IS NOT NULL AND
  OutcomeDemonstration.ExplicitlyEnteredScaleLevelId IS NOT NULL AND
  OutcomeRegistryOwner.OwnerType = 1 AND
  OutcomeRegistryOwner.RegistryId = OutcomeDemonstration.RegistryId AND
  OrgUnit.OrgUnitId = OutcomeRegistryOwner.OwnerId AND
  SKILL_LEVEL_ID = OutcomeDemonstration.ExplicitlyEnteredScaleLevelId
;

COMMIT;

QUIT;
