MERGE INTO
  SSOUSER A
USING
  SSOUSER_LOAD B
ON
  (
    A.SSOUSER_CAMPUS_ID = B.SSOUSER_CAMPUS_ID
  )
WHEN MATCHED THEN
  UPDATE SET
    A.SSOUSER_EMAIL_ADDRESS = B.SSOUSER_EMAIL_ADDRESS,
    A.SSOUSER_FIRST_NAME = B.SSOUSER_FIRST_NAME,
    A.SSOUSER_LAST_NAME = B.SSOUSER_LAST_NAME,
    A.SSOUSER_ACCOUNT_STATUS = B.SSOUSER_ACCOUNT_STATUS,
    A.SSOUSER_ACCOUNT_DISABLED = B.SSOUSER_ACCOUNT_DISABLED,
    A.SSOUSER_AFFILIATIONS = B.SSOUSER_AFFILIATIONS,
    A.SSOUSER_IS_STUDENT = B.SSOUSER_IS_STUDENT,
    A.SSOUSER_IS_FACULTY = B.SSOUSER_IS_FACULTY,
    A.SSOUSER_IS_STAFF = B.SSOUSER_IS_STAFF,
    A.SSOUSER_IS_AFFILIATE = B.SSOUSER_IS_AFFILIATE,
    A.SSOUSER_IS_RETIREE = B.SSOUSER_IS_RETIREE,
    A.SSOUSER_CREATE_DATE = B.SSOUSER_CREATE_DATE,
    A.SSOUSER_UPDATE_DATE = B.SSOUSER_UPDATE_DATE,
    A.SSOUSER_PWD_LAST_SET = B.SSOUSER_PWD_LAST_SET
  WHERE
    NVL(A.SSOUSER_CAMPUS_ID, 0) != NVL(B.SSOUSER_CAMPUS_ID, 0) OR
    NVL(A.SSOUSER_EMAIL_ADDRESS, 0) != NVL(B.SSOUSER_EMAIL_ADDRESS, 0) OR
    NVL(A.SSOUSER_FIRST_NAME, 0) != NVL(B.SSOUSER_FIRST_NAME, 0) OR
    NVL(A.SSOUSER_LAST_NAME, 0) != NVL(B.SSOUSER_LAST_NAME, 0) OR
    NVL(A.SSOUSER_ACCOUNT_STATUS, 0) != NVL(B.SSOUSER_ACCOUNT_STATUS, 0) OR
    NVL(A.SSOUSER_ACCOUNT_DISABLED, 0) != NVL(B.SSOUSER_ACCOUNT_DISABLED, 0) OR
    NVL(A.SSOUSER_AFFILIATIONS, 0) != NVL(B.SSOUSER_AFFILIATIONS, 0) OR
    NVL(A.SSOUSER_IS_STUDENT, 0) != NVL(B.SSOUSER_IS_STUDENT, 0) OR
    NVL(A.SSOUSER_IS_FACULTY, 0) != NVL(B.SSOUSER_IS_FACULTY, 0) OR
    NVL(A.SSOUSER_IS_STAFF, 0) != NVL(B.SSOUSER_IS_STAFF, 0) OR
    NVL(A.SSOUSER_IS_AFFILIATE, 0) != NVL(B.SSOUSER_IS_AFFILIATE, 0) OR
    NVL(A.SSOUSER_IS_RETIREE, 0) != NVL(B.SSOUSER_IS_RETIREE, 0) OR
    NVL(A.SSOUSER_CREATE_DATE, SYSDATE) != NVL(B.SSOUSER_CREATE_DATE, SYSDATE) OR
    NVL(A.SSOUSER_UPDATE_DATE, SYSDATE) != NVL(B.SSOUSER_UPDATE_DATE, SYSDATE) OR
    NVL(A.SSOUSER_PWD_LAST_SET, SYSDATE) != NVL(B.SSOUSER_PWD_LAST_SET, SYSDATE)
WHEN NOT MATCHED THEN
  INSERT
    (
      A.SSOUSER_CAMPUS_ID,
      A.SSOUSER_EMAIL_ADDRESS,
      A.SSOUSER_FIRST_NAME,
      A.SSOUSER_LAST_NAME,
      A.SSOUSER_ACCOUNT_STATUS,
      A.SSOUSER_ACCOUNT_DISABLED,
      A.SSOUSER_AFFILIATIONS,
      A.SSOUSER_IS_STUDENT,
      A.SSOUSER_IS_FACULTY,
      A.SSOUSER_IS_STAFF,
      A.SSOUSER_IS_AFFILIATE,
      A.SSOUSER_IS_RETIREE,
      A.SSOUSER_CREATE_DATE,
      A.SSOUSER_UPDATE_DATE,
      A.SSOUSER_PWD_LAST_SET
    )
  VALUES
    (
      B.SSOUSER_CAMPUS_ID,
      B.SSOUSER_EMAIL_ADDRESS,
      B.SSOUSER_FIRST_NAME,
      B.SSOUSER_LAST_NAME,
      B.SSOUSER_ACCOUNT_STATUS,
      B.SSOUSER_ACCOUNT_DISABLED,
      B.SSOUSER_AFFILIATIONS,
      B.SSOUSER_IS_STUDENT,
      B.SSOUSER_IS_FACULTY,
      B.SSOUSER_IS_STAFF,
      B.SSOUSER_IS_AFFILIATE,
      B.SSOUSER_IS_RETIREE,
      B.SSOUSER_CREATE_DATE,
      B.SSOUSER_UPDATE_DATE,
      B.SSOUSER_PWD_LAST_SET
    )
;

DELETE FROM
  SSOUSER
WHERE
  NOT EXISTS (
    SELECT
      1
    FROM
      SSOUSER_LOAD
    WHERE
      SSOUSER_LOAD.SSOUSER_CAMPUS_ID = SSOUSER.SSOUSER_CAMPUS_ID
  )
;

COMMIT;

QUIT;
