DROP TABLE BNR_SGBSTDN;

CREATE TABLE BNR_SGBSTDN(
  SPRIDEN_PIDM VARCHAR2(8 CHAR) NOT NULL,
  SPRIDEN_ID VARCHAR2(9 CHAR) NOT NULL,
  SGBSTDN_TERM_CODE_EFF VARCHAR2(6 CHAR) NOT NULL,
  SGBSTDN_STST_CODE VARCHAR2(2 CHAR) NOT NULL,
  SGBSTDN_STYP_CODE VARCHAR2(1) NOT NULL,
  SGBSTDN_LEVL_CODE VARCHAR2(2) DEFAULT NULL,
  SGBSTDN_CAMP_CODE VARCHAR2(20) DEFAULT NULL,
  SGBSTDN_COLL_CODE_1 VARCHAR2(2) DEFAULT NULL,
  SGBSTDN_DEPT_CODE VARCHAR2(4) DEFAULT NULL,
  SGBSTDN_DEGC_CODE_1 VARCHAR2(6) DEFAULT NULL,
  SGBSTDN_MAJR_CODE_1 VARCHAR2(4) DEFAULT NULL,
  SGBSTDN_MAJR_CODE_CONC_1 VARCHAR2(4) DEFAULT NULL,
  SGBSTDN_PROGRAM_1 VARCHAR2(20) DEFAULT NULL,
  SGBSTDN_ACTIVITY_DATE DATE NOT NULL,
  SPBPERS_SEX VARCHAR2(6) DEFAULT NULL,
  SPBPERS_AGE NUMBER(8,0) DEFAULT NULL,
  SPBPERS_ETHN_CODE VARCHAR2(50) DEFAULT NULL,
  STU_LEVEL_REGENTS VARCHAR2(2) DEFAULT NULL
);

CREATE INDEX IDX_BNR_SGBSTDN_SPRIDEN_PIDM ON BNR_SGBSTDN (SPRIDEN_PIDM);

QUIT;
