DROP TABLE BNR_STVCODE;

CREATE TABLE BNR_STVCODE (
  STVCODE_TABLE	VARCHAR2(8 CHAR) NOT NULL,
  STVCODE_CODE  VARCHAR2(30 CHAR) NOT NULL,
  STVCODE_DESC	VARCHAR2(60 CHAR) DEFAULT NULL
);

CREATE UNIQUE INDEX BNR_STVCODE_PK ON BNR_STVCODE (STVCODE_TABLE, STVCODE_CODE);

QUIT;
