DROP TABLE BNR_GORPRAC;

CREATE TABLE BNR_GORPRAC (
  GORPRAC_PIDM	    NUMBER(8,0) NOT NULL,
  GORPRAC_RACE_CDE	VARCHAR2(10 CHAR) NOT NULL,
  GORRACE_DESC	    VARCHAR2(60 CHAR) NOT NULL
);

CREATE UNIQUE INDEX BNR_GORPRAC_PK ON BNR_GORPRAC (GORPRAC_PIDM);

QUIT;
