DROP TABLE D2L_ENROLLMENT_SUMMARY;

CREATE TABLE D2L_ENROLLMENT_SUMMARY (
  UserId NUMBER(10) NOT NULL,
  OrgUnitId NUMBER(10) NOT NULL,
  OrgUnitType NVARCHAR2(100) NOT NULL,
  LogIdMin NUMBER(20) DEFAULT NULL,
  LogIdMax NUMBER(20) DEFAULT NULL,
  Action VARCHAR2(100 CHAR) DEFAULT NULL
);

CREATE UNIQUE INDEX PUK_D2L_ENROLLMENT_SUMMARY ON D2L_ENROLLMENT_SUMMARY (UserId, OrgUnitId);
CREATE INDEX IDX_D2L_ENROLLMENT_SUMMARY_USERID ON D2L_ENROLLMENT_SUMMARY (UserId);
CREATE INDEX IDX_D2L_ENROLLMENT_SUMMARY_ORGUNITID ON D2L_ENROLLMENT_SUMMARY (OrgUnitId);
CREATE BITMAP INDEX IDX_D2L_ENROLLMENT_SUMMARY_ORGUNITTYPE ON D2L_ENROLLMENT_SUMMARY (OrgUnitType);
CREATE INDEX IDX_D2L_ENROLLMENT_SUMMARY_LOGIDMIN ON D2L_ENROLLMENT_SUMMARY (LogIdMin);
CREATE INDEX IDX_D2L_ENROLLMENT_SUMMARY_LOGIDMAX ON D2L_ENROLLMENT_SUMMARY (LogIdMax);
CREATE BITMAP INDEX IDX_D2L_ENROLLMENT_SUMMARY_ACTION ON D2L_ENROLLMENT_SUMMARY (Action);

QUIT;
