DROP TABLE SISINST;

CREATE TABLE SISINST (
    SISINST_PIDM NUMBER(8,0) NOT NULL,
    SISINST_TERM_CODE VARCHAR2(6) NOT NULL
);

CREATE UNIQUE INDEX IDX_SISINST_PIDM ON SISINST (SISINST_PIDM);
CREATE BITMAP INDEX IDX_SISINST_TERM_CODE ON SISINST (SISINST_TERM_CODE);

QUIT;
