DROP TABLE SISSECT_LOG;
DROP SEQUENCE SISSECT_LOG_SEQ;

CREATE SEQUENCE SISSECT_LOG_SEQ;
CREATE TABLE SISSECT_LOG (
  SISSECT_LOG_SEQ NUMBER(20) NOT NULL,
  SISSECT_LOG_TIMESTAMP TIMESTAMP WITH LOCAL TIME ZONE NOT NULL, 
  SISSECT_LOG_ACTION CHAR(1) NOT NULL,
  SISSECT_TERM_CODE VARCHAR2(6 CHAR) DEFAULT NULL,
  SISSECT_CRN VARCHAR2(5 CHAR) DEFAULT NULL,
  SISSECT_SUBJ_CODE VARCHAR2(4 CHAR) DEFAULT NULL,
  SISSECT_CRSE_NUMB VARCHAR2(5 CHAR) DEFAULT NULL,
  SISSECT_SEQ_NUMB VARCHAR2(3 CHAR) DEFAULT NULL,
  SISSECT_TITLE VARCHAR2(30 CHAR) DEFAULT NULL,
  SISSECT_CRSE_EFF_TERM VARCHAR2(6 CHAR) DEFAULT NULL,
  SISSECT_CRSE_TITLE VARCHAR2(30 CHAR) DEFAULT NULL,  
  SISSECT_XLST_GROUP VARCHAR2(15 CHAR) DEFAULT NULL,
  SISSECT_DEPT_CODE VARCHAR2(4 CHAR) DEFAULT NULL,
  SISSECT_COLL_CODE VARCHAR2(2 CHAR) DEFAULT NULL,
  SISSECT_TERM_OU_CODE VARCHAR2(50 CHAR) DEFAULT NULL,
  SISSECT_COLL_OU_CODE VARCHAR2(50 CHAR) DEFAULT NULL,
  SISSECT_DEPT_OU_CODE VARCHAR2(50 CHAR) DEFAULT NULL,
  SISSECT_TMPL_OU_CODE VARCHAR2(50 CHAR) DEFAULT NULL,
  SISSECT_OFFR_OU_CODE VARCHAR2(50 CHAR) DEFAULT NULL,
  SISSECT_SECT_OU_CODE VARCHAR2(50 CHAR) DEFAULT NULL,
  SISSECT_ACTIVITY_DATE DATE DEFAULT NULL,
  SISSECT_CREATE_DATE DATE DEFAULT NULL,
  SISSECT_UPDATE_DATE DATE DEFAULT NULL
);

CREATE UNIQUE INDEX PUK_SISSECT_LOG_SEQ ON SISSECT_LOG (SISSECT_LOG_SEQ);
CREATE INDEX IDX_SISSECT_LOG_TIMESTAMP ON SISSECT_LOG (SISSECT_LOG_TIMESTAMP);
CREATE INDEX IDX_SISSECT_LOG_TERM_CRN ON SISSECT_LOG (SISSECT_TERM_CODE, SISSECT_CRN);
CREATE INDEX IDX_SISSECT_LOG_SUBJ_CRSE_SEQ ON SISSECT_LOG (SISSECT_SUBJ_CODE, SISSECT_CRSE_NUMB, SISSECT_SEQ_NUMB);
CREATE INDEX IDX_SISSECT_LOG_SUBJ_CRSE_EFF_TERM ON SISSECT_LOG (SISSECT_SUBJ_CODE, SISSECT_CRSE_NUMB, SISSECT_CRSE_EFF_TERM);
CREATE INDEX IDX_SISSECT_LOG_TERM_XLST_GROUP ON SISSECT_LOG (SISSECT_TERM_CODE, SISSECT_XLST_GROUP);
CREATE INDEX IDX_SISSECT_LOG_OFFR_OU_CODE ON SISSECT_LOG (SISSECT_OFFR_OU_CODE);
CREATE INDEX IDX_SISSECT_LOG_SECT_OU_CODE ON SISSECT_LOG (SISSECT_SECT_OU_CODE);
CREATE INDEX IDX_SISSECT_LOG_ACTIVITY_DATE ON SISSECT_LOG (SISSECT_ACTIVITY_DATE);
CREATE INDEX IDX_SISSECT_LOG_CREATE_DATE ON SISSECT_LOG (SISSECT_CREATE_DATE);
CREATE INDEX IDX_SISSECT_LOG_UPDATE_DATE ON SISSECT_LOG (SISSECT_UPDATE_DATE);
CREATE BITMAP INDEX IDX_SISSECT_LOG_ACTION ON SISSECT_LOG (SISSECT_LOG_ACTION);
CREATE BITMAP INDEX IDX_SISSECT_LOG_COLL_CODE ON SISSECT_LOG (SISSECT_COLL_CODE);
CREATE BITMAP INDEX IDX_SISSECT_LOG_DEPT_CODE ON SISSECT_LOG (SISSECT_DEPT_CODE);
CREATE BITMAP INDEX IDX_SISSECT_LOG_COLL_OU_CODE ON SISSECT_LOG (SISSECT_COLL_OU_CODE);
CREATE BITMAP INDEX IDX_SISSECT_LOG_DEPT_OU_CODE ON SISSECT_LOG (SISSECT_DEPT_OU_CODE);
CREATE BITMAP INDEX IDX_SISSECT_LOG_TMPL_OU_CODE ON SISSECT_LOG (SISSECT_TMPL_OU_CODE);

QUIT;
