DROP TABLE SISSECT;

CREATE TABLE SISSECT (
  SISSECT_TERM_CODE VARCHAR2(6 CHAR) NOT NULL,
  SISSECT_CRN VARCHAR2(5 CHAR) NOT NULL,
  SISSECT_SUBJ_CODE VARCHAR2(4 CHAR) NOT NULL,
  SISSECT_CRSE_NUMB VARCHAR2(5 CHAR) NOT NULL,
  SISSECT_SEQ_NUMB VARCHAR2(3 CHAR) NOT NULL,
  SISSECT_TITLE VARCHAR2(30 CHAR) DEFAULT NULL,
  SISSECT_CRSE_EFF_TERM VARCHAR2(6 CHAR) DEFAULT NULL,
  SISSECT_CRSE_TITLE VARCHAR2(30 CHAR) DEFAULT NULL,  
  SISSECT_XLST_GROUP VARCHAR2(15 CHAR) DEFAULT NULL,
  SISSECT_DEPT_CODE VARCHAR2(4 CHAR) DEFAULT NULL,
  SISSECT_COLL_CODE VARCHAR2(2 CHAR) DEFAULT NULL,
  SISSECT_TERM_OU_CODE VARCHAR2(50 CHAR) DEFAULT NULL,
  SISSECT_COLL_OU_CODE VARCHAR2(50 CHAR) DEFAULT NULL,
  SISSECT_DEPT_OU_CODE VARCHAR2(50 CHAR) DEFAULT NULL,
  SISSECT_TMPL_OU_CODE VARCHAR2(50 CHAR) DEFAULT NULL,
  SISSECT_OFFR_OU_CODE VARCHAR2(50 CHAR) DEFAULT NULL,
  SISSECT_SECT_OU_CODE VARCHAR2(50 CHAR) DEFAULT NULL,
  SISSECT_ACTIVITY_DATE DATE NOT NULL,
  SISSECT_CREATE_DATE DATE NOT NULL,
  SISSECT_UPDATE_DATE DATE NOT NULL
);

CREATE UNIQUE INDEX IDX_SISSECT_TERM_CRN ON SISSECT (SISSECT_TERM_CODE, SISSECT_CRN);
CREATE INDEX IDX_SISSECT_SUBJ_CRSE_SEQ ON SISSECT (SISSECT_SUBJ_CODE, SISSECT_CRSE_NUMB, SISSECT_SEQ_NUMB);
CREATE INDEX IDX_SISSECT_SUBJ_CRSE_EFF_TERM ON SISSECT (SISSECT_SUBJ_CODE, SISSECT_CRSE_NUMB, SISSECT_CRSE_EFF_TERM);
CREATE INDEX IDX_SISSECT_TERM_XLST_GROUP ON SISSECT (SISSECT_TERM_CODE, SISSECT_XLST_GROUP);
CREATE INDEX IDX_SISSECT_OFFR_OU_CODE ON SISSECT (SISSECT_OFFR_OU_CODE);
CREATE INDEX IDX_SISSECT_SECT_OU_CODE ON SISSECT (SISSECT_SECT_OU_CODE);
CREATE INDEX IDX_SISSECT_ACTIVITY_DATE ON SISSECT (SISSECT_ACTIVITY_DATE);
CREATE INDEX IDX_SISSECT_CREATE_DATE ON SISSECT (SISSECT_CREATE_DATE);
CREATE INDEX IDX_SISSECT_UPDATE_DATE ON SISSECT (SISSECT_UPDATE_DATE);
CREATE BITMAP INDEX IDX_SISSECT_COLL_CODE ON SISSECT (SISSECT_COLL_CODE);
CREATE BITMAP INDEX IDX_SISSECT_DEPT_CODE ON SISSECT (SISSECT_DEPT_CODE);
CREATE BITMAP INDEX IDX_SISSECT_COLL_OU_CODE ON SISSECT (SISSECT_COLL_OU_CODE);
CREATE BITMAP INDEX IDX_SISSECT_DEPT_OU_CODE ON SISSECT (SISSECT_DEPT_OU_CODE);
CREATE BITMAP INDEX IDX_SISSECT_TMPL_OU_CODE ON SISSECT (SISSECT_TMPL_OU_CODE);

QUIT;
