DROP TABLE SISSTDN;

CREATE TABLE SISSTDN (
    SISSTDN_PIDM NUMBER(8,0) NOT NULL,
    SISSTDN_TERM_CODE_EFF VARCHAR2(6 CHAR) NOT NULL,
    SISSTDN_STST_CODE VARCHAR2(2 CHAR) NOT NULL,
    SISSTDN_STYP_CODE VARCHAR2(1 CHAR) NOT NULL,
    SISSTDN_COLL_CODE_1 VARCHAR2(2 CHAR) DEFAULT NULL,
    SISSTDN_DEPT_CODE VARCHAR2(4 CHAR) DEFAULT NULL,
    SISSTDN_DEGC_CODE_1 VARCHAR2(6 CHAR) DEFAULT NULL,
    SISSTDN_MAJR_CODE_1 VARCHAR2(4 CHAR) DEFAULT NULL,
    SISSTDN_MAJR_CODE_CONC_1 VARCHAR2(4 CHAR) DEFAULT NULL,
    SISSTDN_PROGRAM_1 VARCHAR2(12 CHAR) DEFAULT NULL,
    SISSTDN_LEVL_CODE VARCHAR2(2 CHAR) DEFAULT NULL,
    SISSTDN_CAMP_CODE VARCHAR2(3 CHAR) DEFAULT NULL,
    SISSTDN_BIRTH_DATE DATE DEFAULT NULL,
    SISSTDN_SEX VARCHAR2(1 CHAR) DEFAULT NULL,
    SISSTDN_ETHN_CODE VARCHAR2(2 CHAR) DEFAULT NULL,
    SISSTDN_RACE_CDE VARCHAR2(12 CHAR) DEFAULT NULL,
    SISSTDN_REGENTS_LEVL_CODE VARCHAR2(2 CHAR) DEFAULT NULL,
    SISSTDN_ACTIVITY_DATE DATE NOT NULL,
    SISSTDN_CREATE_DATE DATE NOT NULL,
    SISSTDN_UPDATE_DATE DATE NOT NULL
);

CREATE UNIQUE INDEX IDX_SISSTDN_PIDM ON SISSTDN (SISSTDN_PIDM);
CREATE INDEX IDX_SISSTDN_BIRTH_DATE ON SISSTDN (SISSTDN_BIRTH_DATE);
CREATE INDEX IDX_SISSTDN_ACTIVITY_DATE ON SISSTDN (SISSTDN_ACTIVITY_DATE);
CREATE INDEX IDX_SISSTDN_CREATE_DATE ON SISSTDN (SISSTDN_CREATE_DATE);
CREATE INDEX IDX_SISSTDN_UPDATE_DATE ON SISSTDN (SISSTDN_UPDATE_DATE);
CREATE BITMAP INDEX IDX_SISSTDN_TERM_CODE_EFF ON SISSTDN (SISSTDN_TERM_CODE_EFF);
CREATE BITMAP INDEX IDX_SISSTDN_STST_CODE ON SISSTDN (SISSTDN_STST_CODE);
CREATE BITMAP INDEX IDX_SISSTDN_STYP_CODE ON SISSTDN (SISSTDN_STYP_CODE);
CREATE BITMAP INDEX IDX_SISSTDN_COLL_CODE_1 ON SISSTDN (SISSTDN_COLL_CODE_1);
CREATE BITMAP INDEX IDX_SISSTDN_DEPT_CODE ON SISSTDN (SISSTDN_DEPT_CODE);
CREATE BITMAP INDEX IDX_SISSTDN_DEGC_CODE_1 ON SISSTDN (SISSTDN_DEGC_CODE_1);
CREATE BITMAP INDEX IDX_SISSTDN_MAJR_CODE_1 ON SISSTDN (SISSTDN_MAJR_CODE_1);
CREATE BITMAP INDEX IDX_SISSTDN_MAJR_CODE_CONC_1 ON SISSTDN (SISSTDN_MAJR_CODE_CONC_1);
CREATE BITMAP INDEX IDX_SISSTDN_PROGRAM_1 ON SISSTDN (SISSTDN_PROGRAM_1);
CREATE BITMAP INDEX IDX_SISSTDN_LEVL_CODE ON SISSTDN (SISSTDN_LEVL_CODE);
CREATE BITMAP INDEX IDX_SISSTDN_CAMP_CODE ON SISSTDN (SISSTDN_CAMP_CODE);
CREATE BITMAP INDEX IDX_SISSTDN_SEX ON SISSTDN (SISSTDN_SEX);
CREATE BITMAP INDEX IDX_SISSTDN_ETHN_CODE ON SISSTDN (SISSTDN_ETHN_CODE);
CREATE BITMAP INDEX IDX_SISSTDN_RACE_CDE ON SISSTDN (SISSTDN_RACE_CDE);
CREATE BITMAP INDEX IDX_SISSTDN_REGENTS_LEVL_CODE ON SISSTDN (SISSTDN_REGENTS_LEVL_CODE);

QUIT;
