DROP TABLE SISTERM;

CREATE TABLE SISTERM (
  SISTERM_ORGUNIT_CODE VARCHAR2(5 CHAR) NOT NULL,
  SISTERM_CODE VARCHAR2(6 CHAR) NOT NULL,
  SISTERM_DESC VARCHAR2(30 CHAR) NOT NULL,
  SISTERM_START_DATE DATE NOT NULL,
  SISTERM_END_DATE DATE NOT NULL,
  SISTERM_IS_PREV VARCHAR2(1 CHAR) DEFAULT NULL,
  SISTERM_IS_CURR VARCHAR2(1 CHAR) DEFAULT NULL,
  SISTERM_IS_NEXT VARCHAR2(1 CHAR) DEFAULT NULL,
  SISTERM_ACTIVITY_DATE DATE NOT NULL,
  SISTERM_CREATE_DATE DATE NOT NULL,
  SISTERM_UPDATE_DATE DATE NOT NULL
);

CREATE UNIQUE INDEX IDX_SISTERM_ORGUNIT_CODE ON SISTERM (SISTERM_ORGUNIT_CODE);
CREATE UNIQUE INDEX IDX_SISTERM_CODE ON SISTERM (SISTERM_CODE);
CREATE INDEX IDX_SISTERM_START_DATE ON SISTERM (SISTERM_START_DATE);
CREATE INDEX IDX_SISTERM_END_DATE ON SISTERM (SISTERM_END_DATE);
CREATE INDEX IDX_SISTERM_ACTIVITY_DATE ON SISTERM (SISTERM_ACTIVITY_DATE);
CREATE INDEX IDX_SISTERM_CREATE_DATE ON SISTERM (SISTERM_CREATE_DATE);
CREATE INDEX IDX_SISTERM_UPDATE_DATE ON SISTERM (SISTERM_UPDATE_DATE);
CREATE BITMAP INDEX IDX_SISTERM_IS_PREV ON SISTERM (SISTERM_IS_PREV);
CREATE BITMAP INDEX IDX_SISTERM_IS_CURR ON SISTERM (SISTERM_IS_CURR);
CREATE BITMAP INDEX IDX_SISTERM_IS_NEXT ON SISTERM (SISTERM_IS_NEXT);

QUIT;
