CREATE OR REPLACE TRIGGER TGR_SISUSER_LOG
AFTER INSERT OR UPDATE OR DELETE ON SISUSER
FOR EACH ROW
DECLARE
  LOG_SEQ NUMBER(20);
  LOG_TIMESTAMP TIMESTAMP WITH LOCAL TIME ZONE;
  LOG_ACTION CHAR(1);
  CAMPUS_ID VARCHAR2(30 CHAR);
  GSU_EMAIL VARCHAR2(128 CHAR);
  FSEM_EMAIL VARCHAR2(128 CHAR);
  FIRST_NAME VARCHAR2(128 CHAR);
  LAST_NAME VARCHAR2(128 CHAR);
  PIDM NUMBER(8,0);
  PANTHER_ID VARCHAR2(9 CHAR);
  SOURCED_ID VARCHAR2(16 CHAR);
  ORG_DEFINED_ID VARCHAR2(20 CHAR);
  ACTIVITY_DATE DATE;
  CREATE_DATE DATE;
  UPDATE_DATE DATE;
BEGIN
  -- Log fields
  LOG_SEQ := SISUSER_LOG_SEQ.NEXTVAL;
  LOG_TIMESTAMP := CURRENT_TIMESTAMP;
  LOG_ACTION := CASE
    WHEN INSERTING THEN 'I'
    WHEN DELETING THEN 'D'
    ELSE 'U'
  END;

  -- Key fields
  PIDM := CASE
    WHEN INSERTING THEN :new.SISUSER_PIDM
    ELSE :old.SISUSER_PIDM
  END;

  -- Everything else
  CAMPUS_ID := CASE
    WHEN INSERTING THEN :new.SISUSER_CAMPUS_ID
    WHEN DELETING THEN NULL
    WHEN NVL(:old.SISUSER_CAMPUS_ID, 0) != NVL(:new.SISUSER_CAMPUS_ID, 0) THEN :new.SISUSER_CAMPUS_ID
  END;
  GSU_EMAIL := CASE
    WHEN INSERTING THEN :new.SISUSER_GSU_EMAIL
    WHEN DELETING THEN NULL
    WHEN NVL(:old.SISUSER_GSU_EMAIL, 0) != NVL(:new.SISUSER_GSU_EMAIL, 0) THEN :new.SISUSER_GSU_EMAIL
  END;
  FSEM_EMAIL := CASE
    WHEN INSERTING THEN :new.SISUSER_FSEM_EMAIL
    WHEN DELETING THEN NULL
    WHEN NVL(:old.SISUSER_FSEM_EMAIL, 0) != NVL(:new.SISUSER_FSEM_EMAIL, 0) THEN :new.SISUSER_FSEM_EMAIL
  END;
  FIRST_NAME := CASE
    WHEN INSERTING THEN :new.SISUSER_FIRST_NAME
    WHEN DELETING THEN NULL
    WHEN NVL(:old.SISUSER_FIRST_NAME, 0) != NVL(:new.SISUSER_FIRST_NAME, 0) THEN :new.SISUSER_FIRST_NAME
  END;
  LAST_NAME := CASE
    WHEN INSERTING THEN :new.SISUSER_LAST_NAME
    WHEN DELETING THEN NULL
    WHEN NVL(:old.SISUSER_LAST_NAME, 0) != NVL(:new.SISUSER_LAST_NAME, 0) THEN :new.SISUSER_LAST_NAME
  END;
  PIDM := CASE
    WHEN INSERTING THEN :new.SISUSER_PIDM
    WHEN DELETING THEN NULL
    WHEN NVL(:old.SISUSER_PIDM, 0) != NVL(:new.SISUSER_PIDM, 0) THEN :new.SISUSER_PIDM
  END;
  PANTHER_ID := CASE
    WHEN INSERTING THEN :new.SISUSER_PANTHER_ID
    WHEN DELETING THEN NULL
    WHEN NVL(:old.SISUSER_PANTHER_ID, 0) != NVL(:new.SISUSER_PANTHER_ID, 0) THEN :new.SISUSER_PANTHER_ID
  END;
  SOURCED_ID := CASE
    WHEN INSERTING THEN :new.SISUSER_SOURCED_ID
    WHEN DELETING THEN NULL
    WHEN NVL(:old.SISUSER_SOURCED_ID, 0) != NVL(:new.SISUSER_SOURCED_ID, 0) THEN :new.SISUSER_SOURCED_ID
  END;
  ORG_DEFINED_ID := CASE
    WHEN INSERTING THEN :new.SISUSER_ORG_DEFINED_ID
    WHEN DELETING THEN NULL
    WHEN NVL(:old.SISUSER_ORG_DEFINED_ID, 0) != NVL(:new.SISUSER_ORG_DEFINED_ID, 0) THEN :new.SISUSER_ORG_DEFINED_ID
  END;
  ACTIVITY_DATE := CASE
    WHEN INSERTING THEN :new.SISUSER_ACTIVITY_DATE
    WHEN DELETING THEN NULL
    WHEN NVL(:old.SISUSER_ACTIVITY_DATE, SYSDATE) != NVL(:new.SISUSER_ACTIVITY_DATE, SYSDATE) THEN :new.SISUSER_ACTIVITY_DATE
  END;
  CREATE_DATE := CASE
    WHEN INSERTING THEN :new.SISUSER_CREATE_DATE
    WHEN DELETING THEN NULL
    WHEN NVL(:old.SISUSER_CREATE_DATE, SYSDATE) != NVL(:new.SISUSER_CREATE_DATE, SYSDATE) THEN :new.SISUSER_CREATE_DATE
  END;
  UPDATE_DATE := CASE
    WHEN INSERTING THEN :new.SISUSER_UPDATE_DATE
    WHEN DELETING THEN NULL
    WHEN NVL(:old.SISUSER_UPDATE_DATE, SYSDATE) != NVL(:new.SISUSER_UPDATE_DATE, SYSDATE) THEN :new.SISUSER_UPDATE_DATE
  END;

  -- Create log record
  INSERT INTO SISUSER_LOG
    (
      SISUSER_LOG_SEQ,
      SISUSER_LOG_TIMESTAMP,
      SISUSER_LOG_ACTION,
      SISUSER_CAMPUS_ID,
      SISUSER_GSU_EMAIL,
      SISUSER_FSEM_EMAIL,
      SISUSER_FIRST_NAME,
      SISUSER_LAST_NAME,
      SISUSER_PIDM,
      SISUSER_PANTHER_ID,
      SISUSER_SOURCED_ID,
      SISUSER_ORG_DEFINED_ID,
      SISUSER_ACTIVITY_DATE,
      SISUSER_CREATE_DATE,
      SISUSER_UPDATE_DATE
    )
  VALUES
    (
      LOG_SEQ,
      LOG_TIMESTAMP,
      LOG_ACTION,
      CAMPUS_ID,
      GSU_EMAIL,
      FSEM_EMAIL,
      FIRST_NAME,
      LAST_NAME,
      PIDM,
      PANTHER_ID,
      SOURCED_ID,
      ORG_DEFINED_ID,
      ACTIVITY_DATE,
      CREATE_DATE,
      UPDATE_DATE
    );
END;
/
QUIT;
/