DROP TABLE SISUSER;

CREATE TABLE SISUSER (
  SISUSER_CAMPUS_ID VARCHAR2(30 CHAR) NOT NULL,
  SISUSER_GSU_EMAIL VARCHAR2(128 CHAR) DEFAULT NULL,
  SISUSER_FSEM_EMAIL VARCHAR2(128 CHAR) DEFAULT NULL,
  SISUSER_FIRST_NAME VARCHAR2(128 CHAR) DEFAULT NULL,
  SISUSER_LAST_NAME VARCHAR2(128 CHAR) NOT NULL,
  SISUSER_PIDM NUMBER(8,0) NOT NULL,
  SISUSER_PANTHER_ID VARCHAR2(9 CHAR) NOT NULL,
  SISUSER_SOURCED_ID VARCHAR2(16 CHAR) NOT NULL,
  SISUSER_ORG_DEFINED_ID VARCHAR2(20 CHAR) NOT NULL,
  SISUSER_ACTIVITY_DATE DATE NOT NULL,
  SISUSER_CREATE_DATE DATE NOT NULL,
  SISUSER_UPDATE_DATE DATE NOT NULL
);

CREATE UNIQUE INDEX IDX_SISUSER_PIDM ON SISUSER (SISUSER_PIDM);
CREATE INDEX IDX_SISUSER_CAMPUS_ID ON SISUSER (SISUSER_CAMPUS_ID);
CREATE INDEX IDX_SISUSER_GSU_EMAIL ON SISUSER (SISUSER_GSU_EMAIL);
CREATE INDEX IDX_SISUSER_FSEM_EMAIL ON SISUSER (SISUSER_FSEM_EMAIL);
CREATE INDEX IDX_SISUSER_LAST_FIRST_NAME ON SISUSER (SISUSER_LAST_NAME, SISUSER_FIRST_NAME);
CREATE INDEX IDX_SISUSER_PANTHER_ID ON SISUSER (SISUSER_PANTHER_ID);
CREATE INDEX IDX_SISUSER_SOURCED_ID ON SISUSER (SISUSER_SOURCED_ID);
CREATE INDEX IDX_SISUSER_ORG_DEFINED_ID ON SISUSER (SISUSER_ORG_DEFINED_ID);
CREATE INDEX IDX_SISUSER_ACTIVITY_DATE ON SISUSER (SISUSER_ACTIVITY_DATE);
CREATE INDEX IDX_SISUSER_CREATE_DATE ON SISUSER (SISUSER_CREATE_DATE);
CREATE INDEX IDX_SISUSER_UPDATE_DATE ON SISUSER (SISUSER_UPDATE_DATE);

QUIT;
