DROP TABLE SKILL_LEVEL;

CREATE TABLE SKILL_LEVEL (
  SKILL_LEVEL_ID VARCHAR2(36 CHAR) NOT NULL,
  SKILL_LEVEL_NAME NVARCHAR2(2000) NOT NULL,
  SKILL_LEVEL_PCTSTART NUMBER(10) NOT NULL,
  SKILL_LEVEL_RGB NVARCHAR2(80) NOT NULL
);

CREATE INDEX IDX_SKILL_LEVEL_ID ON SKILL_LEVEL (SKILL_LEVEL_ID);
CREATE INDEX IDX_SKILL_LEVEL_NAME ON SKILL_LEVEL (SKILL_LEVEL_NAME);
CREATE INDEX IDX_SKILL_LEVEL_PCTSTART ON SKILL_LEVEL (SKILL_LEVEL_PCTSTART);
CREATE INDEX IDX_SKILL_LEVEL_RGB ON SKILL_LEVEL (SKILL_LEVEL_RGB);

QUIT;
