DROP TABLE SKILL_PROGRAM;

CREATE TABLE SKILL_PROGRAM (
  SKILL_PROGRAM_ID NUMBER(20) NOT NULL,
  SKILL_PROGRAM_NAME VARCHAR2(200 CHAR) NOT NULL,
  SKILL_PROGRAM_REGISTRY_ID VARCHAR2(36 CHAR) NOT NULL
);

CREATE INDEX IDX_SKILL_PROGRAM_ID ON SKILL_PROGRAM (SKILL_PROGRAM_ID);
CREATE INDEX IDX_SKILL_PROGRAM_REGISTRY_ID ON SKILL_PROGRAM (SKILL_PROGRAM_REGISTRY_ID);

GRANT SELECT ON SKILL_PROGRAM TO PUBLIC;

QUIT;