DROP TABLE SKILL_ASSESSMENT;

CREATE TABLE SKILL_ASSESSMENT (
  SKILL_ASSESSMENT_ID VARCHAR2(36) NOT NULL,
  SKILL_ASSESSMENT_DETAIL_ID VARCHAR2(36 CHAR) DEFAULT NULL,
  SKILL_ASSESSMENT_OWNER_ID VARCHAR2(36 CHAR) DEFAULT NULL,
  SKILL_ASSESSMENT_DESCRIPTION VARCHAR2(512 CHAR) DEFAULT NULL,
  SKILL_ASSESSMENT_PARENT_ID VARCHAR2(36 CHAR) DEFAULT NULL,
  SKILL_ASSESSMENT_ORGUNIT_ID NUMBER(10) DEFAULT NULL,
  SKILL_ASSESSMENT_ORGUNIT_TYPE NVARCHAR2(100) DEFAULT NULL,
  SKILL_ASSESSMENT_ORGUNIT_CODE NVARCHAR2(100) DEFAULT NULL,
  SKILL_ASSESSMENT_ORGUNIT_NAME NVARCHAR2(256) DEFAULT NULL,
  SKILL_ASSESSMENT_PROGRAM_ID NUMBER(20) DEFAULT NULL,
  SKILL_ASSESSMENT_PROGRAM_NAME VARCHAR2(200 CHAR) DEFAULT NULL,
  SKILL_ASSESSMENT_DETAIL_SOURCE VARCHAR2(8 CHAR) DEFAULT NULL,
  SKILL_ASSESSMENT_DATE TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  SKILL_ASSESSMENT_ASSESSED_USER_ID NUMBER(10) DEFAULT NULL,
  SKILL_ASSESSMENT_ASSESSOR_USER_ID NUMBER(10) DEFAULT NULL,
  SKILL_ASSESSMENT_ALIGNED_OBJECT_TYPE VARCHAR2(10 CHAR) DEFAULT NULL,
  SKILL_ASSESSMENT_ALIGNED_OBJECT_ID NVARCHAR2(2000) DEFAULT NULL,
  SKILL_ASSESSMENT_LEVEL_ID VARCHAR2(36 CHAR) DEFAULT NULL,
  SKILL_ASSESSMENT_LEVEL_NAME NVARCHAR2(2000) DEFAULT NULL,
  SKILL_ASSESSMENT_LEVEL_VALUE NUMBER(10) DEFAULT NULL
);

CREATE UNIQUE INDEX IDX_SKILL_ASSESSMENT_ID ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_ID);
CREATE INDEX IDX_SKILL_ASSESSMENT_DETAIL_ID ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_DETAIL_ID);
CREATE INDEX IDX_SKILL_ASSESSMENT_OWNER_ID ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_OWNER_ID);
CREATE INDEX IDX_SKILL_ASSESSMENT_PARENT_ID ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_PARENT_ID);
CREATE INDEX IDX_SKILL_ASSESSMENT_ORGUNIT_ID ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_ORGUNIT_ID);
CREATE BITMAP INDEX IDX_SKILL_ASSESSMENT_ORGUNIT_TYPE ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_ORGUNIT_TYPE);
CREATE INDEX IDX_SKILL_ASSESSMENT_ORGUNIT_CODE ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_ORGUNIT_CODE);
CREATE INDEX IDX_SKILL_ASSESSMENT_PROGRAM_ID ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_PROGRAM_ID);
CREATE BITMAP INDEX IDX_SKILL_ASSESSMENT_DETAIL_SOURCE ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_DETAIL_SOURCE);
CREATE INDEX IDX_SKILL_ASSESSMENT_DATE ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_DATE);
CREATE INDEX IDX_SKILL_ASSESSMENT_ASSESSED_USER_ID ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_ASSESSED_USER_ID);
CREATE INDEX IDX_SKILL_ASSESSMENT_ASSESSOR_USER_ID ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_ASSESSOR_USER_ID);
CREATE BITMAP INDEX IDX_SKILL_ASSESSMENT_ALIGNED_OBJECT_TYPE ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_ALIGNED_OBJECT_TYPE);
CREATE INDEX IDX_SKILL_ASSESSMENT_ALIGNED_OBJECT_ID ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_ALIGNED_OBJECT_ID);
CREATE INDEX IDX_SKILL_ASSESSMENT_LEVEL_ID ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_LEVEL_ID);
CREATE INDEX IDX_SKILL_ASSESSMENT_LEVEL_NAME ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_LEVEL_NAME);
CREATE INDEX IDX_SKILL_ASSESSMENT_LEVEL_VALUE ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_LEVEL_VALUE);

QUIT;
