DROP TABLE SKILL_OWNER;

CREATE TABLE SKILL_OWNER (
  SKILL_OWNER_ID VARCHAR2(36 CHAR) NOT NULL,
  SKILL_OWNER_ORGUNIT_ID NUMBER(10) DEFAULT NULL,
  SKILL_OWNER_ORGUNIT_TYPE NVARCHAR2(100) DEFAULT NULL,
  SKILL_OWNER_ORGUNIT_CODE NVARCHAR2(100) DEFAULT NULL,
  SKILL_OWNER_ORGUNIT_NAME NVARCHAR2(256) DEFAULT NULL,
  SKILL_OWNER_PROGRAM_ID NUMBER(20) DEFAULT NULL,
  SKILL_OWNER_PROGRAM_NAME VARCHAR2(200 CHAR) DEFAULT NULL
);

CREATE UNIQUE INDEX PUK_SKILL_OWNER ON SKILL_OWNER (SKILL_OWNER_ID);
CREATE INDEX IDX_SKILL_OWNER_ORGUNIT_ID ON SKILL_OWNER (SKILL_OWNER_ORGUNIT_ID);
CREATE BITMAP INDEX IDX_SKILL_OWNER_ORGUNIT_TYPE ON SKILL_OWNER (SKILL_OWNER_ORGUNIT_TYPE);
CREATE INDEX IDX_SKILL_OWNER_ORGUNIT_CODE ON SKILL_OWNER (SKILL_OWNER_ORGUNIT_CODE);
CREATE INDEX IDX_SKILL_OWNER_PROGRAM_ID ON SKILL_OWNER (SKILL_OWNER_PROGRAM_ID);
CREATE INDEX IDX_SKILL_OWNER_PROGRAM_NAME ON SKILL_OWNER (SKILL_OWNER_PROGRAM_NAME);

QUIT;
