DROP TABLE SKILL_ASSESSMENT;

CREATE TABLE SKILL_ASSESSMENT (
  SKILL_ASSESSMENT_PROGRAM_ID NUMBER(20) NOT NULL,
  SKILL_ASSESSMENT_PROGRAM_NAME VARCHAR2(200 CHAR) NOT NULL,
  SKILL_ASSESSMENT_REGISTRY_ID VARCHAR2(36 CHAR) NOT NULL,
  SKILL_ASSESSMENT_DETAIL_ID VARCHAR2(36 CHAR) NOT NULL,
  SKILL_ASSESSMENT_DETAIL_DESCRIPTION VARCHAR2(256 CHAR) NOT NULL,
  SKILL_ASSESSMENT_DETAIL_PARENT_ID VARCHAR2(36 CHAR) DEFAULT NULL,
  SKILL_ASSESSMENT_DETAIL_SOURCE VARCHAR2(8 CHAR) NOT NULL,
  SKILL_ASSESSMENT_COURSE_ID NUMBER(10) NOT NULL,
  SKILL_ASSESSMENT_COURSE_TYPE NVARCHAR2(100) NOT NULL,
  SKILL_ASSESSMENT_COURSE_NAME NVARCHAR2(256) NOT NULL,
  SKILL_ASSESSMENT_COURSE_CODE NVARCHAR2(100) NOT NULL,
  SKILL_ASSESSMENT_ID VARCHAR2(36) NOT NULL,
  SKILL_ASSESSMENT_DATE TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
  SKILL_ASSESSMENT_ASSESSED_USER_ID NUMBER(10) NOT NULL,
  SKILL_ASSESSMENT_ASSESSOR_USER_ID NUMBER(10) NOT NULL,
  SKILL_ASSESSMENT_ALIGNED_OBJECT_TYPE VARCHAR2(10 CHAR) NOT NULL,
  SKILL_ASSESSMENT_ALIGNED_OBJECT_ID NVARCHAR2(2000) NOT NULL,
  SKILL_ASSESSMENT_LEVEL_ID VARCHAR2(36 CHAR) NOT NULL,
  SKILL_ASSESSMENT_LEVEL_NAME NVARCHAR2(2000) NOT NULL,
  SKILL_ASSESSMENT_LEVEL_VALUE NUMBER(10) NOT NULL
);

CREATE INDEX IDX_SKILL_ASSESSMENT_ID ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_ID);
CREATE INDEX IDX_SKILL_ASSESSMENT_DATE ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_DATE);
CREATE INDEX IDX_SKILL_ASSESSMENT_ASSESSED_USER_ID ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_ASSESSED_USER_ID);
CREATE INDEX IDX_SKILL_ASSESSMENT_ASSESSOR_USER_ID ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_ASSESSOR_USER_ID);
CREATE INDEX IDX_SKILL_ASSESSMENT_ALIGNED_OBJECT_ID ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_ALIGNED_OBJECT_ID);
CREATE INDEX IDX_SKILL_ASSESSMENT_PROGRAM_ID ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_PROGRAM_ID);
CREATE INDEX IDX_SKILL_ASSESSMENT_REGISTRY_ID ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_REGISTRY_ID);
CREATE INDEX IDX_SKILL_ASSESSMENT_COURSE_ID ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_COURSE_ID);
CREATE INDEX IDX_SKILL_ASSESSMENT_COURSE_TYPE ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_COURSE_TYPE);
CREATE INDEX IDX_SKILL_ASSESSMENT_COURSE_NAME ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_COURSE_NAME);
CREATE INDEX IDX_SKILL_ASSESSMENT_COURSE_CODE ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_COURSE_CODE);
CREATE INDEX IDX_SKILL_ASSESSMENT_DETAIL_ID ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_DETAIL_ID);
CREATE INDEX IDX_SKILL_ASSESSMENT_DETAIL_PARENT_ID ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_DETAIL_PARENT_ID);
CREATE INDEX IDX_SKILL_ASSESSMENT_LEVEL_ID ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_LEVEL_ID);
CREATE INDEX IDX_SKILL_ASSESSMENT_LEVEL_NAME ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_LEVEL_NAME);
CREATE INDEX IDX_SKILL_ASSESSMENT_LEVEL_VALUE ON SKILL_ASSESSMENT (SKILL_ASSESSMENT_LEVEL_VALUE);

GRANT SELECT ON SKILL_ASSESSMENT TO PUBLIC;

QUIT;