DROP TABLE SSOUSER_LOAD;

CREATE TABLE SSOUSER_LOAD (
  SSOUSER_CAMPUS_ID VARCHAR2(30 CHAR) NOT NULL,
  SSOUSER_EMAIL_ADDRESS VARCHAR2(128 CHAR) NOT NULL,
  SSOUSER_FIRST_NAME VARCHAR2(128 CHAR) NOT NULL,
  SSOUSER_LAST_NAME VARCHAR2(128 CHAR) NOT NULL,
  SSOUSER_ACCOUNT_STATUS VARCHAR2(420 CHAR) NOT NULL,
  SSOUSER_ACCOUNT_DISABLED NUMBER(1) DEFAULT 0 NOT NULL,
  SSOUSER_AFFILIATIONS VARCHAR2(120 CHAR) NOT NULL,
  SSOUSER_IS_STUDENT NUMBER(1) DEFAULT 0 NOT NULL,
  SSOUSER_IS_FACULTY NUMBER(1) DEFAULT 0 NOT NULL,
  SSOUSER_IS_STAFF NUMBER(1) DEFAULT 0 NOT NULL,
  SSOUSER_IS_AFFILIATE NUMBER(1) DEFAULT 0 NOT NULL,
  SSOUSER_IS_RETIREE NUMBER(1) DEFAULT 0 NOT NULL,
  SSOUSER_CREATE_DATE TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  SSOUSER_UPDATE_DATE TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  SSOUSER_PWD_LAST_SET TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL
);

CREATE UNIQUE INDEX IDX_SSOUSER_LOAD_CAMPUS_ID ON SSOUSER_LOAD (SSOUSER_CAMPUS_ID);
CREATE INDEX IDX_SSOUSER_LOAD_EMAIL_ADDRESS ON SSOUSER_LOAD (SSOUSER_EMAIL_ADDRESS);
CREATE INDEX IDX_SSOUSER_LOAD_NAME ON SSOUSER_LOAD (SSOUSER_LAST_NAME, SSOUSER_FIRST_NAME);
CREATE INDEX IDX_SSOUSER_LOAD_ACCOUNT_STATUS ON SSOUSER_LOAD (SSOUSER_ACCOUNT_STATUS);
CREATE INDEX IDX_SSOUSER_LOAD_AFFILIATIONS ON SSOUSER_LOAD (SSOUSER_AFFILIATIONS);
CREATE INDEX IDX_SSOUSER_LOAD_CREATE_DATE ON SSOUSER_LOAD (SSOUSER_CREATE_DATE);
CREATE INDEX IDX_SSOUSER_LOAD_UPDATE_DATE ON SSOUSER_LOAD (SSOUSER_UPDATE_DATE);
CREATE INDEX IDX_SSOUSER_LOAD_PWD_LAST_SET ON SSOUSER_LOAD (SSOUSER_PWD_LAST_SET);
CREATE BITMAP INDEX IDX_SSOUSER_LOAD_ACCOUNT_DISABLED ON SSOUSER_LOAD (SSOUSER_ACCOUNT_DISABLED);
CREATE BITMAP INDEX IDX_SSOUSER_LOAD_IS_STUDENT ON SSOUSER_LOAD (SSOUSER_IS_STUDENT);
CREATE BITMAP INDEX IDX_SSOUSER_LOAD_IS_FACULTY ON SSOUSER_LOAD (SSOUSER_IS_FACULTY);
CREATE BITMAP INDEX IDX_SSOUSER_LOAD_IS_STAFF ON SSOUSER_LOAD (SSOUSER_IS_STAFF);
CREATE BITMAP INDEX IDX_SSOUSER_LOAD_IS_AFFILIATE ON SSOUSER_LOAD (SSOUSER_IS_AFFILIATE);
CREATE BITMAP INDEX IDX_SSOUSER_LOAD_IS_RETIREE ON SSOUSER_LOAD (SSOUSER_IS_RETIREE);

QUIT;
